// See https://svelte.dev/docs/kit/types#app.d.ts
// ExecutionContext, D1Database, and RateLimit below are ambient globals from
// worker-configuration.d.ts (generated by `wrangler types`, wired into tsconfig.json's "files"),
// not an import: `wrangler types` superseded @cloudflare/workers-types as of wrangler 4.x, and
// its own generated `Env` interface is deliberately unused here in favor of the explicit
// Platform.env shape below, since wrangler.toml carries only the D1/R2/rate-limit bindings, not
// the Worker secrets (TURNSTILE_SECRET_KEY, STRIPE_*, DISCORD_WEBHOOK_*) this site also reads.
// The binding-shaped types ship from the /sveltekit subpath, so the Platform block intersects
// them rather than restating every engine binding by hand. CairnMediaBindings adds
// MEDIA_BUCKET, present because this site turns media on.
import type { CairnPlatformBindings, CairnMediaBindings } from '@glw907/cairn-cms/sveltekit';
import type { MemberRow } from '$member-auth/lib/auth';
// The engine's own four `cairn*`-prefixed locals keys (`cairnEditor`, `cairnBackend`,
// `cairnAuditSink`, `cairnAccess`) ship here, so nothing below restates one. `cairnAuditSink` in
// particular is the engine's declaration, not this site's: hooks.server.ts writes it, and
// duplicating the field here would have hidden the `0.94.0-rc.1` rename behind a site-owned type
// that still compiled.
import '@glw907/cairn-cms/ambient';

declare global {
  namespace App {
    interface Locals {
      // Set by /my-account/+layout.server.ts's own session resolve (a member session, distinct
      // from the engine's own `locals.editor`; the two stores never blur). `null` when signed
      // out or the session has expired; absent (`undefined`) outside the /my-account route tree.
      member?: MemberRow | null;
    }
    interface Platform {
      // EVENTS_DB is this site's own binding (Task 4), not a cairn-cms one: the club's ops-stack
      // D1, read (never written) for the Season section and /events. See
      // src/theme/season-data.ts's header comment. CLUB_DB is pass 2.1's own domain store (the
      // asc-club side of the two-database strategy; migrations/asc-club/), read AND written by
      // the Club section's own screens (resolved everywhere via src/admin-club/lib/club-db.ts's
      // resolveClubDb). TURNSTILE_SECRET_KEY, STRIPE_SECRET_KEY, and
      // STRIPE_WEBHOOK_SECRET are site-owned Worker secrets (contact.remote.ts,
      // donate.remote.ts, payments.ts, the api/stripe/webhook route), set with `wrangler secret
      // put`, never committed; each is optional here so the site keeps degrading gracefully
      // wherever the secret is absent, rather than every caller having to satisfy a required
      // field this environment has not always provisioned. DISCORD_WEBHOOK_ASSETS and
      // DISCORD_WEBHOOK_CLASSES are the same kind of optional Worker secret, read by
      // admin-club/lib/discord.ts's notifyDiscord (docs/discord-notifications-wiring.md); this
      // declaration is not required for a notifyDiscord call site to type-check (its own
      // DiscordBindingEnv is a structural subset any superset already satisfies), but keeps this
      // environment's own type declarations in sync with what `wrangler secret list` names. The
      // remaining nine DISCORD_WEBHOOK_* fields are the Announce screen's own channel vocabulary
      // (discord.ts's ANNOUNCE_CHANNELS); as of this writing only GENERAL, SITE, FLEET,
      // EDUCATION, RACING, HARBOR, and TECHNOLOGY are real secrets, LEADERSHIP and BUCCANEER_18
      // are declared but unset, and the Announce screen's own "not configured" note is how that
      // gap surfaces to an admin rather than a silent no-op.
      env: CairnPlatformBindings &
        CairnMediaBindings & {
          EVENTS_DB: D1Database;
          CLUB_DB: D1Database;
          TURNSTILE_SECRET_KEY?: string;
          STRIPE_SECRET_KEY?: string;
          STRIPE_WEBHOOK_SECRET?: string;
          // The payments-live-smoke hardening pass's rate-limit namespaces (wrangler.toml's
          // `[[ratelimits]]` block, `src/theme/rate-limit.ts` the shared wrapper); each optional
          // for the same reason TURNSTILE_SECRET_KEY is: an unprovisioned environment (local dev,
          // vitest) degrades to open rather than requiring every caller to satisfy a binding this
          // environment has not always provisioned.
          RATE_LIMIT_MONEY?: RateLimit;
          RATE_LIMIT_PUBLIC_POST?: RateLimit;
          RATE_LIMIT_MEMBER?: RateLimit;
          RATE_LIMIT_ADMIN?: RateLimit;
          RATE_LIMIT_ENUMERATION?: RateLimit;
          DISCORD_WEBHOOK_ASSETS?: string;
          DISCORD_WEBHOOK_CLASSES?: string;
          DISCORD_WEBHOOK_LEADERSHIP?: string;
          DISCORD_WEBHOOK_GENERAL?: string;
          DISCORD_WEBHOOK_SITE?: string;
          DISCORD_WEBHOOK_FLEET?: string;
          DISCORD_WEBHOOK_EDUCATION?: string;
          DISCORD_WEBHOOK_RACING?: string;
          DISCORD_WEBHOOK_BUCCANEER_18?: string;
          DISCORD_WEBHOOK_HARBOR?: string;
          DISCORD_WEBHOOK_TECHNOLOGY?: string;
          // The visual suite's fixed clock (`YYYY-MM-DD`), set only on the e2e server
          // (playwright.config.ts passes it to `wrangler dev --var`), never in wrangler.toml and
          // never in production. `/events` reads it so its past/upcoming judgments hold still
          // between baseline runs. A binding, not a request header or a query parameter, so
          // nothing a visitor sends can shift what the public page calls past.
          ASC_FIXED_TODAY?: string;
          // Email + Announce pass, Task 2 (src/admin-club/lib/email-limits.ts): the advisory
          // quota headroom check against the account's Email Sending allowance.
          // CLOUDFLARE_ACCOUNT_ID is a `wrangler.toml` `[vars]` value (mirrors that file's own
          // top-level `account_id` deploy field, which the Worker runtime cannot read).
          // CLOUDFLARE_EMAIL_SENDING_TOKEN is a Worker secret, read-only Email Sending scope,
          // optional here because it may never be minted at all (a supported, permanent
          // degrade-to-unknown state, not a transient gap; see the design doc's "Data and
          // infrastructure" section).
          CLOUDFLARE_ACCOUNT_ID?: string;
          CLOUDFLARE_EMAIL_SENDING_TOKEN?: string;
        };
      context: ExecutionContext;
      caches: CacheStorage & { default: Cache };
    }
  }
}

export {};
